package com.redhat.demos.albertsons;

import org.kie.dmn.feel.lang.FEELProperty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String name;
	private java.time.LocalDateTime hireDate;
	private java.math.BigDecimal baseSalary;
	private java.math.BigDecimal regularHourPayRate;

	public Employee() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	@FEELProperty("hire date")
	public java.time.LocalDateTime getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(java.time.LocalDateTime hireDate) {
		this.hireDate = hireDate;
	}

	@FEELProperty("base salary")
	public java.math.BigDecimal getBaseSalary() {
		return this.baseSalary;
	}

	public void setBaseSalary(java.math.BigDecimal baseSalary) {
		this.baseSalary = baseSalary;
	}

	@FEELProperty("hourly rate")
	public java.math.BigDecimal getRegularHourPayRate() {
		return this.regularHourPayRate;
	}

	public void setRegularHourPayRate(java.math.BigDecimal regularHourPayRate) {
		this.regularHourPayRate = regularHourPayRate;
	}

	public Employee(java.lang.Long id, java.lang.String name,
			java.time.LocalDateTime hireDate, java.math.BigDecimal baseSalary,
			java.math.BigDecimal regularHourPayRate) {
		this.id = id;
		this.name = name;
		this.hireDate = hireDate;
		this.baseSalary = baseSalary;
		this.regularHourPayRate = regularHourPayRate;
	}

	@Override
	public String toString() {
		return "{" +
			" id='" + getId() + "'" +
			", name='" + getName() + "'" +
			", hireDate='" + getHireDate() + "'" +
			", baseSalary='" + getBaseSalary() + "'" +
			", regularHourPayRate='" + getRegularHourPayRate() + "'" +
			"}";
	}

}