package com.redhat.demos.albertsons;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkSheet implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public WorkSheet() {
    }




}