package com.redhat.demos.albertsons;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkSheet implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.Long employeeId;
	private java.util.List<WorkingHour> worksheet;

	public WorkSheet() {
		this.worksheet = new ArrayList<WorkingHour>();
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(java.lang.Long employeeId) {
		this.employeeId = employeeId;
	}

	public java.util.List<WorkingHour> getWorksheet() {
		return this.worksheet;
	}

	public void setWorksheet(java.util.List<WorkingHour> worksheet) {
		this.worksheet = worksheet;
	}

	public void addWorkingHour(WorkingHour workingHour){
		this.worksheet.add(workingHour);
	}

	public WorkSheet(java.lang.Long id, java.lang.Long employeeId,
			java.util.List<WorkingHour> worksheet) {
		this.id = id;
		this.employeeId = employeeId;
		this.worksheet = worksheet;
	}

	@Override
	public String toString() {
		return "{" +
			" id='" + getId() + "'" +
			", employeeId='" + getEmployeeId() + "'" +
			", worksheet='" + getWorksheet() + "'" +
			"}";
	}

}